import {test} from 'node:test';
import assert from 'node:assert/strict';
import {FluxConnect} from '../src/connect.ts';
import {FluxUsage} from '../src/usage.ts';
import {FluxState} from '../src/index.ts';
function store(){const map=new Map();const s={map,get:async k=>structuredClone(map.get(k)),put:async(k,v)=>map.set(k,structuredClone(v)),delete:async k=>map.delete(k),transaction:async cb=>cb(s)};return s;}
const env={FLUX_CONNECT_KEY:'ab'.repeat(32),SPOTIFY_CLIENT_ID:'client'};
const req=(path,body={})=>new Request('https://flux.test'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
async function authorize(c,id='spotify'){const r=await(await c.route(req(`/v1/connect/${id}/start`))).json();return new URL(r.url);}
test('connector routes require Core authentication; no token exposed in catalog',async()=>{const c=new FluxState({storage:store()},{FLUX_AUTH_TOKEN:'a'.repeat(32)});assert.equal((await c.fetch(new Request('https://flux.test/v1/connect'))).status,401);const catalog=await(new FluxConnect(store(),env)).route(new Request('https://flux.test/v1/connect'));assert.equal(JSON.stringify(await catalog.json()).includes(env.FLUX_CONNECT_KEY),false);});
test('OAuth uses S256 and encrypted one-use state, token remains encrypted at rest',async()=>{const s=store();let called=0;const c=new FluxConnect(s,env,async(url,opts)=>{called++;assert.equal(url,'https://accounts.spotify.com/api/token');const form=new URLSearchParams(opts.body);assert.equal(form.get('grant_type'),'authorization_code');const hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(form.get('code_verifier')))).toString('base64url');assert.equal(hash,start.searchParams.get('code_challenge'));return Response.json({access_token:'private-access-token',refresh_token:'private-refresh',expires_in:3600});});const start=await authorize(c);assert.equal(start.searchParams.get('code_challenge_method'),'S256');assert.equal(JSON.stringify([...s.map]).includes('verifier'),false);const callback='https://flux.test/v1/connect/callback/spotify?code=one-use-code&state='+start.searchParams.get('state');assert.equal((await c.callbackRequest(new Request(callback))).status,200);assert.equal(JSON.stringify([...s.map]).includes('private-access-token'),false);await assert.rejects(()=>c.callbackRequest(new Request(callback)),e=>e.status===400);assert.equal(called,1);});
test('wrong-provider OAuth callback rejected before credential exchange',async()=>{let calls=0;const c=new FluxConnect(store(),env,async()=>{calls++;return Response.json({});});const start=await authorize(c);await assert.rejects(()=>c.callbackRequest(new Request('https://flux.test/v1/connect/callback/gmail?code=x&state='+start.searchParams.get('state'))),e=>e.status===400);assert.equal(calls,0);});
test('missing OAuth app config and wrong encryption key fail without external calls',async()=>{let calls=0;const c=new FluxConnect(store(),{},async()=>{calls++;return Response.json({});});await assert.rejects(()=>authorize(c),e=>e.status===503);assert.equal(calls,0);});
test('revocation drops local token and test evidence; Spotify control requires confirmation',async()=>{let controls=0;const s=store();const c=new FluxConnect(s,env,async(url)=>{if(url.includes('/api/token'))return Response.json({access_token:'token',expires_in:3600});if(url.endsWith('/me/player/pause')){controls++;return new Response(null,{status:204});}return Response.json({id:'profile',is_playing:false});});const start=await authorize(c);await c.callbackRequest(new Request('https://flux.test/v1/connect/callback/spotify?code=x&state='+start.searchParams.get('state')));await assert.rejects(()=>c.route(req('/v1/connect/spotify/action',{action:'pause'})),e=>e.status===403);assert.equal(controls,0);const action=await(await c.route(req('/v1/connect/spotify/action',{action:'pause',confirm:true}))).json();assert.equal(action.providerHttpStatus,204);assert.equal(action.verification.is_playing,false);assert.equal(controls,1);await c.route(req('/v1/connect/spotify/revoke'));assert.equal(await s.get('connect:grant:spotify'),undefined);await assert.rejects(()=>c.route(req('/v1/connect/spotify/test')),e=>e.status===409);});
test('route quotas survive instance replacement and budget is explicitly an estimate',async()=>{const s=store();await s.put('usage:'+new Date().toISOString().slice(0,7),{imageRequests:300});await assert.rejects(()=>new FluxUsage(s).reserve('imageRequests'),e=>e.status===429);const summary=await(await new FluxUsage(s).route(new Request('https://flux.test/v1/usage'))).json();assert.equal(summary.hardCapGuaranteed,false);assert.equal(summary.providerInvoiceAvailable,false);assert.equal(summary.observedGatewayAttempts.imageRequests,300);});

test('local revocation works when Google remote revocation fails',async()=>{const s=store();const c=new FluxConnect(s,{...env,GOOGLE_CLIENT_ID:'client',GOOGLE_CLIENT_SECRET:'secret'},async(url)=>{if(url.includes('/token'))return Response.json({access_token:'token',expires_in:3600});throw new Error('network unavailable');});const start=await authorize(c,'gmail');await c.callbackRequest(new Request('https://flux.test/v1/connect/callback/gmail?code=x&state='+start.searchParams.get('state')));const result=await(await c.route(req('/v1/connect/gmail/revoke'))).json();assert.equal(result.localRevoked,true);assert.equal(result.providerRevoked,false);assert.equal(await s.get('connect:grant:gmail'),undefined);});
test('SmartThings uses documented confidential OAuth and checks real device capabilities before commands',async()=>{let commands=0;const s=store();const cfg={...env,SMARTTHINGS_CLIENT_ID:'client',SMARTTHINGS_CLIENT_SECRET:'secret'};const c=new FluxConnect(s,cfg,async(url,opts)=>{if(url.endsWith('/oauth/token')){assert.equal(opts.headers.authorization,'Basic '+btoa('client:secret'));assert.equal(new URLSearchParams(opts.body).has('code_verifier'),false);return Response.json({access_token:'token',expires_in:86400});}if(url.endsWith('/commands')){commands++;return new Response(null,{status:200});}if(url.endsWith('/status'))return Response.json({components:{main:{switch:{switch:{value:'on'}}}}});return Response.json({components:[{id:'main',capabilities:[{id:'switch'}]}]});});const start=await authorize(c,'smartthings');assert.equal(start.searchParams.has('code_challenge'),false);await c.callbackRequest(new Request('https://flux.test/v1/connect/callback/smartthings?code=x&state='+start.searchParams.get('state')));const deviceId='80e26532-85d4-484c-b012-1c04f3d35f95';await assert.rejects(()=>c.route(req('/v1/connect/smartthings/action',{action:'play',deviceId,confirm:true})),e=>e.status===409);assert.equal(commands,0);const r=await(await c.route(req('/v1/connect/smartthings/action',{action:'on',deviceId,confirm:true}))).json();assert.equal(commands,1);assert.equal(r.verification.components.main.switch.switch.value,'on');await assert.rejects(()=>c.route(req('/v1/connect/smartthings/action',{action:'off',deviceId:'../outside',confirm:true})),e=>e.status===400);});
