import assert from 'node:assert/strict';
import {test,afterEach} from 'node:test';
import {FluxState} from '../src/index.ts';
import {EvolutionWorkspace,readBoundedObject} from '../src/evolution.ts';
const originalFetch=globalThis.fetch;
afterEach(()=>{globalThis.fetch=originalFetch;});
function storage(){const values=new Map();const s={get:async key=>structuredClone(values.get(key)),put:async(key,value)=>values.set(key,structuredClone(value)),delete:async key=>values.delete(key),transaction:async callback=>callback(s),setAlarm:async time=>{s.alarmAt=time;}};return s;}
function request(path,body,method=body?'POST':'GET',authorized=true){return new Request('https://flux.test'+path,{method,headers:{'content-type':'application/json',...(authorized?{authorization:'Bearer '+ 'a'.repeat(32)}:{})},...(body?{body:JSON.stringify(body)}:{})});}
function core(s=storage()){return new FluxState({storage:s},{FLUX_AUTH_TOKEN:'a'.repeat(32),INWORLD_API_KEY:'test-secret'});}
const memory={title:'Estudo',content:'Prefiro exemplos de Fórmula 1.',category:'preference',consent:true};
test('all new routes reject unauthenticated callers',async()=>{for(const path of ['/v1/memories','/v1/missions','/v1/vision'])assert.equal((await core().fetch(request(path,undefined,'GET',false))).status,401);});
test('memory requires consent; persists, corrects and erases content',async()=>{const s=storage();const c=core(s);assert.equal((await c.fetch(request('/v1/memories',{...memory,consent:false}))).status,400);const created=await(await c.fetch(request('/v1/memories',memory))).json();const id=created.memory.id;assert.equal((await core(s).fetch(request('/v1/memories'))).status,200);assert.equal((await c.fetch(request('/v1/memories/'+id,{...memory,content:'Prefiro exemplos visuais.'},'PATCH'))).status,200);assert.equal((await c.fetch(request('/v1/memories/'+id,undefined,'DELETE'))).status,200);assert.deepEqual((await(await c.fetch(request('/v1/memories'))).json()).memories,[]);});
test('credentials and invalid expiry are rejected by memory',async()=>{const c=core();for(const changes of [{content:'api_key=example-secret'},{expiresAt:'2020-01-01'}])assert.equal((await c.fetch(request('/v1/memories',{...memory,...changes}))).status,400);});
test('expired memories are excluded from retrieval',async()=>{const s=storage();await s.put('evolution:memories',[{...memory,id:'x',expiresAt:'2020-01-01'}]);const w=new EvolutionWorkspace(s,async()=> 'ok');assert.equal(await w.memoryContext('Estudo'),'');});
test('queued mission survives instance replacement and completes only after executor',async()=>{const s=storage();const w=new EvolutionWorkspace(s,async prompt=>{assert.match(prompt,/Não declare envio/);return 'Explicação com dois exercícios.';});const {mission}=await(await w.createMission({kind:'study',objective:'Revisar biologia'})).json();assert.ok(s.alarmAt>Date.now());assert.equal((await w.missions())[0].status,'queued');await new EvolutionWorkspace(s,async()=> 'Explicação com dois exercícios.').alarm();const done=(await w.missions())[0];assert.equal(done.id,mission.id);assert.equal(done.status,'completed');assert.equal(done.output,'Explicação com dois exercícios.');assert.deepEqual(done.events.map(x=>x.state),['queued','running','completed']);});
test('mission provider failure is visible and never marked complete',async()=>{const w=new EvolutionWorkspace(storage(),async()=>{throw new Error('secret error');});await w.createMission({kind:'draft',objective:'Texto'});await w.alarm();const item=(await w.missions())[0];assert.equal(item.status,'failed');assert.equal(JSON.stringify(item).includes('secret error'),false);});
test('cancelling a running mission cannot be overwritten by a late result',async()=>{let resolve;const w=new EvolutionWorkspace(storage(),()=>new Promise(r=>{resolve=r;}));const {mission}=await(await w.createMission({kind:'code',objective:'Proposta'})).json();const running=w.alarm();while(!resolve)await new Promise(r=>setImmediate(r));await w.cancelMission(mission.id);resolve('Resultado tardio');await running;assert.equal((await w.missions())[0].status,'cancelled');assert.equal((await w.missions())[0].output,undefined);});
test('mission queue is bounded and unsupported side effects have no executor',async()=>{const w=new EvolutionWorkspace(storage(),async()=> 'ok');for(let i=0;i<5;i++)await w.createMission({kind:'draft',objective:'Texto '+i});await assert.rejects(()=>w.createMission({kind:'draft',objective:'Mais'}),error=>error.status===429);await assert.rejects(()=>w.createMission({kind:'send-email',objective:'Enviar'}),error=>error.status===400);});
test('oversized bodies and invalid JSON are rejected before parsing',async()=>{await assert.rejects(()=>readBoundedObject(request('/',{data:'a'.repeat(100)}),20),error=>error.status===413);await assert.rejects(()=>readBoundedObject(new Request('https://flux.test',{method:'POST',body:'broken',headers:{'content-type':'application/json'}})),error=>error.status===400);});
test('vision sends the real image to a multimodal provider without storing it',async()=>{const s=storage();const c=core(s);const image='data:image/png;base64,iVBORw0KGgo=';globalThis.fetch=async(url,options)=>{const body=JSON.parse(options.body);assert.equal(body.max_tokens,1000);assert.equal(body.messages.at(-1).content[1].image_url.url,image);assert.match(body.messages[0].content,/nunca ordens/);return Response.json({choices:[{message:{content:'O texto é FLUX.'}}]});};const result=await(await c.fetch(request('/v1/vision',{image,prompt:'Leia o texto.'}))).json();assert.equal(result.content,'O texto é FLUX.');assert.equal(result.imageStored,false);assert.equal(await s.get('evolution:images'),undefined);});
test('vision rejects remote URLs before any external request',async()=>{globalThis.fetch=()=>{throw new Error('should not fetch');};assert.equal((await core().fetch(request('/v1/vision',{image:'https://private.example/a.png',prompt:'Leia'}))).status,400);});
test('deep Inworld generations stay within plan token limit',async()=>{globalThis.fetch=async(url,options)=>{assert.equal(JSON.parse(options.body).max_tokens,1000);return Response.json({choices:[{message:{content:'Código'} }]});};assert.equal((await core().fetch(request('/v1/chat',{requestId:crypto.randomUUID(),conversationId:'test',message:'Programe uma função e explique a arquitetura em detalhes'}))).status,200);});
test('Workers AI visual and text configuration is explicit and bypasses Inworld',async()=>{const calls=[];const c=new FluxState({storage:storage()},{FLUX_AUTH_TOKEN:'a'.repeat(32),INWORLD_API_KEY:'test-secret',FLUX_TEXT_PROVIDER:'workers-ai',FLUX_VISION_PROVIDER:'workers-ai',AI:{run:async(model,input)=>{calls.push([model,input]);return {response:'12, círculo vermelho e 4827'};}}});globalThis.fetch=()=>{throw new Error('Inworld should not run');};const visual=await c.fetch(request('/v1/vision',{image:'data:image/png;base64,iVBORw0KGgo=',prompt:'Leia'}));assert.equal((await visual.json()).provider,'cloudflare-workers-ai');assert.equal(calls[0][0],'@cf/meta/llama-4-scout-17b-16e-instruct');assert.equal((await c.fetch(request('/v1/chat',{requestId:crypto.randomUUID(),conversationId:'cf-test',message:'Olá'}))).status,200);});
test('Inworld billing failure is actionable and non-retryable HTTP 402',async()=>{globalThis.fetch=async()=>new Response('{}',{status:402});for(const [path,body] of [['/v1/tts',{text:'teste'}],['/v1/vision',{image:'data:image/png;base64,iVBORw0KGgo=',prompt:'Leia'}],['/v1/chat',{requestId:crypto.randomUUID(),conversationId:'billing',message:'Olá'}]]){const response=await core().fetch(request(path,body));assert.equal(response.status,402);assert.match((await response.json()).message,/créditos/);}});
test('image provider error returns visible failure without logging prompt or raw error',async()=>{const s=storage();const c=new FluxState({storage:s},{FLUX_AUTH_TOKEN:'a'.repeat(32),AI:{run:async()=>{throw new Error('5001 private secret response');}}});const response=await c.fetch(request('/v1/images',{prompt:'A private photo idea'}));assert.equal(response.status,503);assert.equal(JSON.stringify(await response.json()).includes('private'),false);assert.deepEqual(Object.keys(await s.get('evolution:image-provider-error')).sort(),['at','code']);});
